//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himalayan_Angular.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquiry
    {
        public int EnquiryId { get; set; }
        public int ProductId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerMobile { get; set; }
        public string Message { get; set; }
    
        public virtual ProductMain ProductMain { get; set; }
    }
}
